# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c0e33e7da4616f944f0044cfb6f889c519c22b3e398659a14cd211ec47d0ff8794cdcd8fb33998632d970e1ed0e06729244cec622cd73bf05b68dea70509b2

test:
  secret_key_base: 2b2e4247453ee145e503bd72d123d8607af06867eae0282f8fd3fa0d53c1f8ac50b8344550c20c2f7b7e3af9a9284c1fe7f8544986fc47b341242e171934e4fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
